cargo-features = ['edition']

[package]
name = "vyper"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = '2018'


[dependencies]
pyo3 = "0.4.1"
failure = "0.1.2"
log = "*"
pretty_env_logger = "*"
