[package]
name = "emul"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]

[dependencies]
rustc-hex = "1.0"
ethereum-types = "0.3"
log = "0.3"
crossbeam = "0.3"
tempdir = "0.3"
delegate = "0.1.3"
keccak-hash = { git = "https://github.com/paritytech/parity-common" }
kvdb = { git = "https://github.com/paritytech/parity-common" }
kvdb-rocksdb = { git = "https://github.com/paritytech/parity-common" }
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
rlp = { git = "https://github.com/paritytech/parity-common" }
kvdb-memorydb = { git = "https://github.com/paritytech/parity-common"}

[dependencies.journaldb]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.blooms-db]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.evm]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.vm]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.ethcore]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.ethcore-transaction]
git = "https://github.com/ethdbg/parity"
branch = "edb"

[dependencies.ethcore-io]
git = "https://github.com/ethdbg/parity"
branch = "edb"
