[package]
name = "emul"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]

[dependencies]
evm = { git = "https://github.com/paritytech/parity" }
vm = { git = "https://github.com/paritytech/parity" }
ethcore = { git = "https://github.com/paritytech/parity" }
ethcore-bytes = { git = "https://github.com/paritytech/parity" }
keccak-hash = { git = "https://github.com/paritytech/parity" }
rlp = { git = "https://github.com/paritytech/parity" }
ethcore-transaction = { git = "https://github.com/paritytech/parity" }
ethcore-io = { git = "https://github.com/paritytech/parity" }


rustc-hex = "1.0"
ethereum-types = "0.3"
log = "0.3"
crossbeam = "0.3"
# shrinkwraprs = "0.2.0" useful for newtypes
