cargo-features = ['edition']

[package]
name = "compiler"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = '2018'


[dependencies]
pyo3 = "0.4.1"
failure = "0.1.2"
log = "*"
pretty_env_logger = "*"
solc = {git = "https://github.com/paritytech/rust_solc.git" }
ethereum-types = "0.4.0"
serde_json = "1.0.27"
serde_derive = "1.0.78"
serde = "1.0.78"
serde_test = "1.0.78"
